"""Date + random word slug generation (e.g. 2026-03-13-electric-penguin)."""

from __future__ import annotations

import datetime
import random
import re

_ADJECTIVES = (
    "alpine",
    "amber",
    "arctic",
    "azure",
    "bold",
    "brave",
    "bright",
    "brisk",
    "calm",
    "cedar",
    "civic",
    "clear",
    "clever",
    "coral",
    "cosmic",
    "crisp",
    "dapper",
    "dawn",
    "deep",
    "deft",
    "dusky",
    "eager",
    "early",
    "earthy",
    "electric",
    "even",
    "fair",
    "fern",
    "firm",
    "fleet",
    "focal",
    "fresh",
    "gentle",
    "gilt",
    "golden",
    "grand",
    "hardy",
    "hazel",
    "hearty",
    "ivory",
    "jade",
    "keen",
    "kind",
    "lapis",
    "leafy",
    "light",
    "linen",
    "lively",
    "lunar",
    "maple",
    "marble",
    "mellow",
    "mint",
    "mossy",
    "neat",
    "nimble",
    "noble",
    "north",
    "oaken",
    "olive",
    "open",
    "outer",
    "pastel",
    "pearl",
    "pine",
    "placid",
    "polar",
    "prime",
    "quiet",
    "rapid",
    "regal",
    "ridge",
    "rustic",
    "sandy",
    "serene",
    "sharp",
    "silver",
    "sleek",
    "solar",
    "south",
    "steady",
    "still",
    "stone",
    "sturdy",
    "sunny",
    "swift",
    "tidal",
    "timber",
    "topaz",
    "vivid",
    "warm",
    "west",
    "whole",
    "windy",
    "wise",
)

_NOUNS = (
    "anchor",
    "atlas",
    "basin",
    "beacon",
    "birch",
    "bridge",
    "brook",
    "canopy",
    "canyon",
    "cedar",
    "cliff",
    "coast",
    "compass",
    "cove",
    "crane",
    "crest",
    "delta",
    "dune",
    "falcon",
    "fern",
    "field",
    "fjord",
    "flint",
    "forge",
    "frost",
    "glade",
    "grove",
    "harbor",
    "haven",
    "hawk",
    "heath",
    "heron",
    "hill",
    "horizon",
    "inlet",
    "isle",
    "jasper",
    "juniper",
    "kite",
    "lagoon",
    "lark",
    "laurel",
    "ledge",
    "linden",
    "lodge",
    "mantle",
    "marsh",
    "meadow",
    "mesa",
    "mist",
    "north",
    "oasis",
    "orchid",
    "otter",
    "pebble",
    "pelican",
    "penguin",
    "pier",
    "pine",
    "pixel",
    "plain",
    "plover",
    "pond",
    "prism",
    "quartz",
    "raven",
    "reef",
    "ridge",
    "river",
    "robin",
    "sage",
    "shore",
    "sierra",
    "slate",
    "spruce",
    "stone",
    "summit",
    "swift",
    "tarn",
    "terra",
    "thicket",
    "timber",
    "trail",
    "trellis",
    "vale",
    "valley",
    "vista",
    "wren",
)


def generate_slug(label: str | None = None) -> str:
    """Generate a dated slug for a new session.

    No label: YYYY-MM-DD-adj-noun (random)
    With label: YYYY-MM-DD-kebab-cased-label
    """
    date = datetime.date.today().isoformat()

    if label is not None:
        kebab = label.lower().strip()
        kebab = re.sub(r"\s+", "-", kebab)
        kebab = re.sub(r"[^a-z0-9-]", "", kebab)
        return f"{date}-{kebab}"

    adj = random.choice(_ADJECTIVES)
    noun = random.choice(_NOUNS)
    return f"{date}-{adj}-{noun}"
